- hosts: localhost
  connection: local

  roles:
    # 1. Base System & Shell
    #    (Common utilities, directory setup, basic Zsh config)
    - common
    - zsh

    # 2. Development Tools (Roles)
    #    (Installation and config deployment for specific tools)
    - nvim
    - wezterm
    - tmux
    - aerospace

    # 3. Global Packages
    #    (Install global CLI tools and GUI apps from all.yml)
    #- homebrew
